### PR TITLE
 updated code for method, action, name and id for form tag

### PR DESCRIPTION
**Pull request by voletiswaroop**
This Module enables the adding method, action, name, and id for the form tag

### CODE REVIEW

**Comment by galki** [comment]
@voletiswaroop are you ready to merge?

**Comment by voletiswaroop** [comment]
Yes, I'm ready to merge @galki. 
I have done the changes only in 'src/components/Form.js' file after the build the code updated in respective places

**Comment by voletiswaroop** [comment]
I have done the changes in only in 'src/components/Form.js' file after the build the code updated in respective places

**Comment by voletiswaroop** [comment]
Hi @galki,

Due to the urgency in my current project, I have extended this module with above fix and published it to NPM. 

**Note:** I have mentioned in my npm module "This project is an extended version of https://github.com/unitedhubs/material-ui-form/".

Let me know if anything?

**Comment by galki** [comment]
@voletiswaroop I'm sorry to have made you wait again. I have just started switching to Angular. Would you like to take over maintenance?

**Comment by voletiswaroop** [comment]
Apologies for the delay in response, Yes ill take it forward for maintenance. @galki

**Pull request merged**
